# Site settings
title: "Oliver Steele"
author: Oliver Steele
email: steele@osteele.com
# description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://osteele.com" # the base hostname & protocol for your site
timezone: America/New_York
twitter_username: osteele
github_username:  osteele
copyright-range: 1998-2017

exclude: [".htaccess", "docker-compose.yml", "Gemfile", "Gemfile.lock", "previous"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highligher: pygments

# theme: jekyll-theme-minimal
